jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

spring:
  datasource:
    url: jdbc:postgresql://${RDS_ENDPOINT}:5432/${RDS_DB_NAME}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
#    repair-on-migrate: true
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        packagesToScan: com.example.Piroin.project.domain

management:
  endpoints:
    web:
      exposure:
        include: health
